### ISSUE TITLE
Error while compiling CryptX (AIX 7.3, XL C/C++ 16.1)

### ISSUE THREAD

**Issue by edugerlach** [DCIT/perl-CryptX#117]
Hello team,

I have recently upgraded from AIX 7.2 to 7.3, and I am recompiling some perl modules. When I attempt "make install", I am getting this error:

Skip blib/lib/Crypt/Digest/Keccak512.pm (unchanged)
Skip blib/lib/Crypt/Cipher/RC2.pm (unchanged)
Skip blib/lib/Crypt/Digest/SHA3_256.pm (unchanged)
Skip blib/lib/Crypt/Cipher/SAFER_K128.pm (unchanged)
        cd src && make ARFLAGS="cr" RANLIB=":" AR="ar" CC="xlc_r -q32" LIB_EXT=.a OBJ_EXT=.o CFLAGS=" -D_ALL_SOURCE -D_ANSI_C_SOURCE -D_POSIX_SOURCE -qmaxmem=-1 -qnoansialias -qlanglvl=extc99 -DUSE_NATIVE_DLOPEN -DNEED_PTHREAD_INIT -q32 -D_LARGE_FILES   -O "
        xlc_r -q32 -Iltm -Iltc/headers -DLTC_SOURCE -DLTC_NO_TEST -DLTC_NO_PROTOTYPES -DLTM_DESC -D_ALL_SOURCE -D_ANSI_C_SOURCE -D_POSIX_SOURCE -qmaxmem=-1 -qnoansialias -qlanglvl=extc99 -DUSE_NATIVE_DLOPEN -DNEED_PTHREAD_INIT -q32 -D_LARGE_FILES   -O  -DARGTYPE=4 -c ltc/ciphers/aes/aes.c -o ltc/ciphers/aes/aes.o
"ltc/headers/tomcrypt_private.h", line 20.1: 1506-195 (S) Integral constant expression with a value greater than zero is required.
make: 1254-004 The error code from the last command is 1.

Stop.
make: 1254-004 The error code from the last command is 2.

Stop.

Note.: I have applied an update to xlc after AIX went to 7.3. So now it's running version: 16.1.0.19.
Note2.: There's no network connectivity on this AIX box, so I manually download and install dependencies.

Any help is appreciated.

**Comment by karel-m** [comment]
What CryptX version are you trying to install?

**Comment by karel-m** [comment]
@sjaeckel looks like an AIX/xlc specific issue related to this line in `tomcrypt_private.h`:
```
LTC_STATIC_ASSERT(correct_CONSTPTR_size, sizeof(CONSTPTR(1)) == sizeof(void*))
```

**Comment by sjaeckel** [comment]
> [@sjaeckel](https://github.com/sjaeckel) looks like an AIX/xlc specific issue

True.

I already had a quick look before and I basically came to the same conclusion.

FMU your configuration leads to ltc being built with the `xlc` flag `-q32` which "selects 32-bit compiler mode" as of [0], page 104f. As of [1] your update to AIX 7.3 indicates that you have at least a POWER8 CPU [2] so it is definitely 64-bit capable, but maybe you want smaller object code, so you're compiling with `-q32`, which is fine.

IMO the correct patch would be something in the area of what we did in [3], but I couldn't figure out yet what the exact compiler macros should be to test on and what the correct configuration is in the end. If I understand [4] correctly, the patch should basically be the exact same as [3], or am I mistaken?

> [@edugerlach](https://github.com/edugerlach) could you please try to comment out the line
> 
> ```
> LTC_STATIC_ASSERT(correct_CONSTPTR_size, sizeof(CONSTPTR(1)) == sizeof(void*))
> ```
> 
> in `tomcrypt_private.h`?

@edugerlach some questions:
1. If you do that and the compile succeeds, what do the tests say?
2. Which are the compiler warnings emitted?
3. Which was the last version of CryptX that compiled&tested successfully?

@karel-m Maybe it'd also make sense to enable the `-qwarn64` flag (c.f. [0], page 435)?

[0] https://www.ibm.com/docs/en/SSGH3R_16.1.0/pdf/compiler.pdf
[1] https://en.wikipedia.org/wiki/IBM_AIX
[2] https://en.wikipedia.org/wiki/POWER8
[3] https://github.com/libtom/libtomcrypt/commit/d96605b4b90d72012a21400cac54ff1b5d94611f
[4] https://www.ibm.com/docs/en/zos/2.4.0?topic=issues-data-type-assignment-differences-under-ilp32-lp64

**Comment by edugerlach** [comment]
Hello to both of you,
First, I'd like to say that I did not think I was going to be so well assisted by people interested in really understanding how things work and what's needed to fix them. So, thank you. 

To answer to your questions, Karen:

The CryptX version I am installing is the latest available in CPAN --> CryptX-0.084.

I have removed line 20, and I was able to finish compiling it.
Thank you again, and I am available to help with other questions you may have to possibly work on a fix for this.

**Comment by sjaeckel** [comment]
> [@edugerlach](https://github.com/edugerlach) some questions:
> 
>     1. If you do that and the compile succeeds, what do the tests say?
> 
>     2. Which are the compiler warnings emitted?
> 
>     3. Which was the last version of CryptX that compiled&tested successfully?

Would you mind answering those questions?

The background is: the line you removed exists for a reason and failed your build for a reason. Maybe CryptX compiled now successfully, but that doesn't mean that it's also functioning correctly.

**Comment by edugerlach** [comment]
Hello, I am sorry for the delay.

1. The success criteria in my case were some perl scripts that application teams had schedule in our environment since forever. After compiling without line 20, their scripts worked. So I'd say "real life testes" were good.
2. I will adhere a lot for the entire compilation, after removing line 20. Maybe you can go through it in detail. 
3. We were running AIX 7.2 for some time, with perl at 5.28.1.8 and CryptX at:

# cpan -l | grep Crypt::PRNG
Crypt::PRNG     0.069
Crypt::PRNG::ChaCha20   0.069
Crypt::PRNG::Fortuna    0.069
Crypt::PRNG::RC4        0.069
Crypt::PRNG::Sober128   0.069
Crypt::PRNG::Yarrow     0.069
Crypt::PRNG     0.069
Crypt::PRNG::ChaCha20   0.069
Crypt::PRNG::Fortuna    0.069
Crypt::PRNG::RC4        0.069
Crypt::PRNG::Sober128   0.069
Crypt::PRNG::Yarrow     0.069

I hope this helps.

[Crypt--PRNG_aix_compilation_logs.txt](https://github.com/user-attachments/files/18707109/Crypt--PRNG_aix_compilation_logs.txt)

**Comment by karel-m** [comment]
Have you run the CryptX test suite? (I mean `make test`)

**Comment by edugerlach** [comment]
I think I got excited that "perl Makefile.pl configure" worked that I went directly to "make".
So, I won't have that one. But if you want, I can try to simulate this in a lab.

**Comment by thomasseeling-ibm** [comment]
I ran into the same problem, and I've got the same environment. I *can* compile with `gcc`, if I manually edit the generated `Makefile`, but I'm not sure if I can mix binaries from `xlc_r` (`perl` interpreter is compiled with this) with libraries compiled by `gcc`.

I changed the macro in `src/ltc/headers/tomcrypt_private.h` to an empty definition, and I could then compile with `xlc_r` but I'd like to be sure that the code still works. The `assert` tries to establish that a `void *` has the same size as a `long long`, and I assume there are some typecasts to that effect in the code. `xlc_r` balks out because of the illegal (?) `-1` result. I have no idea what this assert should do, because a function call with that particular name is nowhere in the code.

```
9,10c9,11
< /* Static assertion */
< #define LTC_STATIC_ASSERT(msg, cond) typedef char ltc_static_assert_##msg[(cond) ? 1 : -1];
---
> /* Static assertion
> #define LTC_STATIC_ASSERT(msg, cond) typedef char ltc_static_assert_##msg[(cond) ? 1 : -1]; */
> #define LTC_STATIC_ASSERT(msg, cond)
```

**Comment by sjaeckel** [comment]
Long story short - `xlc_r -q32` also produces machine code in the `ILP32` format.

IMO the solution for that case would be to rename `ENDIAN_64BITWORD_X32` to `ENDIAN_64BITWORD_ILP32`, check for that as well for aix and define it there.

**Comment by sjaeckel** [comment]
@karel-m could you please create a test release of CryptX with that patch included, so @thomasseeling-ibm or @edugerlach can try it out?

**Comment by karel-m** [comment]
> could you please create a test release of CryptX with that patch included

done https://metacpan.org/release/MIK/CryptX-0.085_001

**Comment by thomasseeling-ibm** [comment]
> > could you please create a test release of CryptX with that patch included
> done https://metacpan.org/release/MIK/CryptX-0.085_001

works for me, `make test` is successfull.
```
...
t/sshkey.t .......................... ok
All tests successful.
Files=137, Tests=25241, 63 wallclock secs ( 0.84 usr  0.16 sys + 16.34 cusr  3.46 csys = 20.80 CPU)
Result: PASS
```

**Comment by sjaeckel** [comment]
@karel-m please update ltc once more before release, since the latest PR contains a fix of the DER decoder.

**Comment by sjaeckel** [comment]
FTR the Debian x32 tests still fail, I'll have a look into it soon.

Since x32 is also ILP32, AIX will most likely need to be retested.

**Comment by karel-m** [comment]
@sjaeckel I have updated ltc to [3905c2](https://github.com/libtom/libtomcrypt/commit/3905c28913232d6e82a2a381cc2b71b0af7aa791). Does this commit work with Debian x32 / ILP32?

**Comment by sjaeckel** [comment]
> [@sjaeckel](https://github.com/sjaeckel) I have updated ltc to [3905c2](https://github.com/libtom/libtomcrypt/commit/3905c28913232d6e82a2a381cc2b71b0af7aa791). Does this commit work with Debian x32 / ILP32?

doesn't seem so ... looks like I broke the build!? :( https://buildd.debian.org/status/package.php?p=libcryptx-perl

https://buildd.debian.org/status/fetch.php?pkg=libcryptx-perl&arch=x32&ver=0.085-1&stamp=1742486668&raw=0
```
In file included from ltc/ciphers/aes/aes.c:25:
ltc/headers/tomcrypt_private.h:10:51: error: size of array ‘ltc_static_assert_correct_CONSTPTR_size’ is negative
   10 | #define LTC_STATIC_ASSERT(msg, cond) typedef char ltc_static_assert_##msg[(cond) ? 1 : -1];
      |                                                   ^~~~~~~~~~~~~~~~~~
ltc/headers/tomcrypt_private.h:20:1: note: in expansion of macro ‘LTC_STATIC_ASSERT’
   20 | LTC_STATIC_ASSERT(correct_CONSTPTR_size, sizeof(CONSTPTR(1)) == sizeof(void*))
      | ^~~~~~~~~~~~~~~~~
ltc/ciphers/aes/aes.c: In function ‘rijndael_setup’:
ltc/headers/tomcrypt_private.h:31:32: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   31 | #define LTC_ALIGN_BUF(buf, n) ((void*)((ltc_uintptr)&((unsigned char*)(buf))[n - 1] & (~(CONSTPTR(n) - CONSTPTR(1)))))
      |                                ^
ltc/ciphers/aes/aes.c:115:9: note: in expansion of macro ‘LTC_ALIGN_BUF’
  115 |     K = LTC_ALIGN_BUF(skey->rijndael.K, 16);
      |         ^~~~~~~~~~~~~
make[2]: *** [Makefile:199: ltc/ciphers/aes/aes.o] Error 1
make[2]: Leaving directory '/<<PKGBUILDDIR>>/src'
make[1]: *** [Makefile:1937: src/liballinone.a] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by sjaeckel** [comment]
hmmmm, now I'm a bit surprised ...

```
$ sudo apt update
$ sudo apt install gcc-x86-64-linux-gnux32 git build-essential
$ git clone https://github.com/libtom/libtomcrypt.git
$ CROSS_COMPILE=x86_64-linux-gnux32- make -j33 test
[...]
$ file test
test: ELF 32-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /libx32/ld-linux-x32.so.2, BuildID[sha1]=26cdd128397630119786711774e8250782082788, for GNU/Linux 3.4.0, not stripped
```

I can't run it, because I don't have a kernel running which allows running x32 binaries and I don't want to spend more time.

@gregoa - could you please have a look?
